### PR TITLE
added type hints to functions and methods

### PR DESCRIPTION
**Pull request by Packan1337**
added as many as i could, however a lot of parameter names have no type hints as i didnt have time to figure out their data types

### CODE REVIEW

**Comment by israelias** [comment]
@Packan1337 Your timing is great. Literally just pushed a bunch in the last 8 hours to bring the backend back to life on https://thrifthub-backend.onrender.com (there's no data) Still in the middle of migrating the pgsql ever since Heroku died in November.

This looks awesome. Lemme have a look.

**Comment by Packan1337** [comment]
You're welcome :D, lemme know if you need more help with anything

**Comment by israelias** [comment]
@Packan1337 Well matey you got me inspired to get this back online this weekend and also a little embarrassed by the state of the docs and mono #RepoOps as nothing is live. The 2021 S3 bucket is blocking a clean db sync. I'll just wipe it. Stay tuned I'm hitting you up !

**Comment by Packan1337** [comment]
For sure!

**Pull request merged**
